version: '3'
services:
  ekz_view:
    container_name: ekz_view
    build: ./ekz_view/v2
    command: "/root/ekz_view/entrypoint.sh"
    env_file: /etc/opt/app_setting_files/ekz_container/.env
    ports:
      - "18070:18072"
    volumes:
      - ./ekz_view/v2:/root/ekz_view
    environment:
      NODE_ENV: ${ENV:-development} # 本番実行時は`ENV=production docker-compose up`

  ekz_api:
    container_name: ekz_api
    build: ./ekz_api
    command: "/root/ekz_api/entrypoint.sh"
    ports:
      - "18030:18030"
    env_file: /etc/opt/app_setting_files/ekz_container/.env
    volumes:
      - ./ekz_api:/root/ekz_api

  ekz_api_nest:
    container_name: ekz_api_nest
    build: ./ekz_api_nest
    command: "/root/ekz_api_nest/entrypoint.sh"
    ports:
      - "18031:3000"
    env_file: /etc/opt/app_setting_files/ekz_container/.env
    volumes:
      - ./ekz_api_nest:/root/ekz_api_nest

  ekz_chrome:
    image: seleniarm/node-chromium:4.3.0-20220709
    shm_size: 2gb
    depends_on:
      - ekz_selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=ekz_selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  ekz_selenium_hub:
    image: selenium/hub:4.3.0-20220726
    container_name: ekz_selenium_hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"