version: '3'
services:
  ekz_api:
    container_name: ekz_api
    build: ./ekz_api
    command: "/root/ekz_api/entrypoint.sh"
    ports:
      - "18071:18071"
    env_file: /etc/opt/app_setting_files/ekz_container/.env
    volumes:
      - ./ekz_api:/root/ekz_api